### ISSUE TITLE
Correction in line 195

### ISSUE THREAD

**Issue by panzi999** [AK-Homberger/NMEA2000-SeatalkNG-AlarmBuzzer#1]
Hi Andreas,

I think lines 195/196 "pinMode(9, ALARM_PIN);" 
should read "
195 pinMode(ALARM_PIN,OUTPUT);
196 digitalWrite(ALARM_PIN, false);"

Then the software works fine for me. Thanks a lot, Ralf.

**Comment by AK-Homberger** [comment]
Thanks for reporting the issue. Code is corrected now.
